confirm-before-quit = false

[window]
width = 850
height = 480
opacity = 0.8

[renderer]
level = 1

[fonts]
family = "Inconsolata"
size = 14

# since 0.2.1 https://github.com/raphamorim/rio/releases/tag/v0.2.1
# Rio now allows you to have different configurations per OS, you can write ovewrite `Shell`, `Navigation` and `Window`.


[platform]
# Microsoft Windows overwrite
windows.shell.program = "pwsh"
windows.shell.args = ["-l"]

# Linux overwrite
#linux.shell.program = "tmux"
#linux.shell.args = ["new-session", "-c", "/var/www"]
