# https://docs.rubocop.org/rubocop/1.29/configuration.html

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlightment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false
