export LANG="zh_CN.UTF-8"
export LC_ALL="zh_CN.UTF-8"

# 2018,06,06 fcitx
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE=fcitx
export GTK3_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx

#exec start-lumina-desktop

#exec /usr/local/bin/startxfce4

# https://wiki.freebsd.org/LXQt
# http://lxqt-freebsd.schmitz.computer/
#ck-launch-session /usr/local/bin/startlxqt

#exec ck-launch-session startkde

#exec /usr/local/bin/startfluxbox

#exec ck-launch-session gnome-session

exec ck-launch-session mate-session

#exec startplasma-x11
